export const GET_TWEETS_FROM_FOLLOWED_USERS_REQUEST = 'GET_TWEETS_FROM_FOLLOWED_USERS_REQUEST';
export const GET_TWEETS_FROM_FOLLOWED_USERS_SUCCESS = 'GET_TWEETS_FROM_FOLLOWED_USERS_SUCCESS';
export const GET_TWEETS_FROM_FOLLOWED_USERS_FAILURE = 'GET_TWEETS_FROM_FOLLOWED_USERS_FAILURE';

export const CREATE_TWEET_REQUEST = 'CREATE_TWEET_REQUEST';
export const CREATE_TWEET_SUCCESS = 'CREATE_TWEET_SUCCESS';
export const CREATE_TWEET_FAILURE = 'CREATE_TWEET_FAILURE';

export const GET_ALL_TWEETS_REQUEST = 'GET_ALL_TWEETS_REQUEST';
export const GET_ALL_TWEETS_SUCCESS = 'GET_ALL_TWEETS_SUCCESS';
export const GET_ALL_TWEETS_FAILURE = 'GET_ALL_TWEETS_FAILURE';

export const GET_TWEET_BY_ID_REQUEST = 'GET_TWEET_BY_ID_REQUEST';
export const GET_TWEET_BY_ID_SUCCESS = 'GET_TWEET_BY_ID_SUCCESS';
export const GET_TWEET_BY_ID_FAILURE = 'GET_TWEET_BY_ID_FAILURE';

export const UPDATE_TWEET_REQUEST = 'UPDATE_TWEET_REQUEST';
export const UPDATE_TWEET_SUCCESS = 'UPDATE_TWEET_SUCCESS';
export const UPDATE_TWEET_FAILURE = 'UPDATE_TWEET_FAILURE';

export const DELETE_TWEET_REQUEST = 'DELETE_TWEET_REQUEST';
export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS';
export const DELETE_TWEET_FAILURE = 'DELETE_TWEET_FAILURE';


